FROM s390x/ubuntu:17.10

ENV container docker

LABEL architecture="s390x" \
      name="gluster/gluster-ubuntu" \
      version="3.10" \
      summary="This image has a running glusterfs service (Ubuntu 17.10 + Gluster 3.10)" \
      io.k8s.display-name="Gluster 3.10 based on Ubuntu 17.10" \
      io.k8s.description="Gluster Image is based on Ubuntu Image which is a scalable network filesystem. Using common off-the-shelf hardware, you can create large, distributed storage solutions for media streaming, data analysis, and other data- and bandwidth-intensive tasks." \
      description="Gluster Image is based on Ubuntu Image which is a scalable network filesystem. Using common off-the-shelf hardware, you can create large, distributed storage solutions for media streaming, data analysis, and other data- and bandwidth-intensive tasks." \
      io.openshift.tags="gluster,glusterfs,glusterfs-ubuntu"

RUN ["/bin/bash", "-c", "apt-get update; apt-get install -y systemd; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;\
apt-get install -y glusterfs-client glusterfs-server glusterfs-common ntp lvm2 rsync xfsprogs iproute tar sudo attr wget nfs-common openssh-client openssh-server thin-provisioning-tools module-init-tools; "]

RUN sed -i '/Defaults    requiretty/c\#Defaults    requiretty' /etc/sudoers; \
sed -i '/Port 22/c\Port 2222' /etc/ssh/sshd_config; \
sed -i 's/Requires\=rpcbind\.service//g' /usr/lib/systemd/system/glusterd.service; \
sed -i 's/rpcbind\.service/gluster-setup\.service/g' /usr/lib/systemd/system/glusterd.service; \
sed -i 's/ENV{DM_UDEV_DISABLE_OTHER_RULES_FLAG}=="1", ENV{SYSTEMD_READY}="0"/ENV{DM_UDEV_DISABLE_OTHER_RULES_FLAG}=="1", GOTO="systemd_end"/g' /lib/udev/rules.d/99-systemd.rules; \
mkdir -p /etc/glusterfs_bkp /var/lib/glusterd_bkp /var/log/glusterfs_bkp;cp -r /etc/glusterfs/* /etc/glusterfs_bkp;cp -r /var/lib/glusterd/* /var/lib/glusterd_bkp;cp -r /var/log/glusterfs/ /var/log/glusterfs_bkp; \
sed -i.save -e "s#udev_sync = 1#udev_sync = 0#" -e "s#udev_rules = 1#udev_rules = 0#" -e "s#use_lvmetad = 1#use_lvmetad = 0#" /etc/lvm/lvm.conf;

VOLUME [ "/sys/fs/cgroup" ]

# Adding script to move the glusterfs config file to location
ADD gluster-setup.service /etc/systemd/system/gluster-setup.service

# Adding script to move the glusterfs config file to location
ADD gluster-setup.sh /usr/sbin/gluster-setup.sh

RUN chmod 644 /etc/systemd/system/gluster-setup.service; \
chmod 500 /usr/sbin/gluster-setup.sh; \
systemctl disable nfs-common.service; \
systemctl mask getty.target; \
systemctl enable ntp.service; \
systemctl enable glusterd.service; \
systemctl enable gluster-setup.service;

EXPOSE 2222 111 245 443 24007 2049 8080 6010 6011 6012 38465 38466 38468 38469 49152 49153 49154 49156 49157 49158 49159 49160 49161 49162

CMD ["/sbin/init"]
